/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module buttons_mux_19 (
    input [6:0] buttons_sel,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 16'h0000;
    
    case (buttons_sel)
      1'h1: begin
        out = 16'h0fc0;
      end
      2'h2: begin
        out = 16'h0061;
      end
      3'h4: begin
        out = 16'h0083;
      end
      4'h8: begin
        out = 16'h0106;
      end
      5'h10: begin
        out = 16'h020c;
      end
      6'h20: begin
        out = 16'h0418;
      end
      7'h40: begin
        out = 16'h0830;
      end
    endcase
  end
endmodule
