/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module levels_mux_13 (
    input [1:0] levels_sel,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 16'h0000;
    
    case (levels_sel)
      1'h0: begin
        out = 16'h0f9e;
      end
      1'h1: begin
        out = 16'h074c;
      end
      2'h2: begin
        out = 16'h0c94;
      end
      2'h3: begin
        out = 16'h090e;
      end
    endcase
  end
endmodule
